---
kind: pipeline
type: kubernetes
name: build-page

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: squidfunk/mkdocs-material
  commands:
  - git remote add gh-token "https://$${GH_TOKEN}@github.com/lib42/lib42.github.io"
  - git fetch gh-token && git checkout gh-token/docs
  - wget -O docs/projects/incubating/heqet.md -nv https://raw.githubusercontent.com/nold360/heqet/master/README.md
  - "echo -e '\n## Project URL\n\nhttps://github.com/nold360/heqet' >> docs/projects/incubating/heqet.md"
  - wget -O docs/projects/incubating/charts.md -nv https://raw.githubusercontent.com/lib42/charts/master/README.md
  - "echo -e '\n## Project URL\n\nhttps://github.com/lib42/charts' >> docs/projects/incubating/charts.md"
  - wget -O docs/projects/stable/docker-borgserver.md -nv https://raw.githubusercontent.com/nold360/docker-borgserver/master/README.md
  - "echo -e '\n## Project URL\n\nhttps://github.com/nold360/docker-borgserver' >> docs/projects/stable/docker-borgserver.md"
  - cp README.md docs/index.md
  - mkdocs gh-deploy --remote-name gh-token --remote-branch main
  environment:
    GH_TOKEN:
      from_secret: gh_token

...
