---
kind: pipeline
type: kubernetes
name: build-page

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: squidfunk/mkdocs-material
  commands:
  - git remote add gh-token "https://$${GH_TOKEN}@github.com/lib42/lib42.github.io"
  - git fetch gh-token && git checkout gh-token/main
  - wget -O projects/incubating/heqet.md -nv https://raw.githubusercontent.com/nold360/heqet/master/README.md
  - wget -O projects/incubating/charts.md -nv https://raw.githubusercontent.com/lib42/charts/master/README.md
  - wget -O projects/stable/docker-borgserver.md -nv https://raw.githubusercontent.com/nold360/docker-borgserver/master/README.md
  - ls -l
  - ls -l docs
  - mkdocs gh-deploy --remote-name gh-token --remote-branch main
  environment:
    GH_TOKEN:
      from_secret: gh_token

...
